version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/leave_management
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345 # Must match POSTGRES_PASSWORD
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=leave_management
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345 # Must match SPRING_DATASOURCE_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d leave_management"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
